config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'

  namespace :api do
    resources :menus, only: [:index, :show, :create, :delete]
    resources :restaurants, only: :index
    resources :calories, only: [:index, :show]
    resources :image_uploaders, only: :create
  end

  namespace :admin do
    root to: 'menus#index'
    resources :menus, only: :index
    resources :restaurants, only: :index
    resources :categories
    resources :tags
  end

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :categories, only: :index
  resources :tags, only: [:index, :show]
  resources :menus, only: :show
  resources :activities, only: [:index, :create, :thanks]
  resources :restaurants, only: :show

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :menu
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calorie.rb
class Calorie < ApplicationRecord
  has_many :menus
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :menu_categories
  has_many :menus, through: :menu_categories
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :user_menus
  has_many :user, through: :user_menus
  has_many :menu_categories
  has_many :categories, through: :menu_categories
  has_many :menu_tags
  has_many :tags, through: :menu_tags
  has_many :user_menus
  has_many :users, through: :user_menus
  has_one :restaurant

  validates :calorie_id, presence: true

  accepts_nested_attributes_for :categories, :tags, :restaurant
end

app/models/menu_category.rb
class MenuCategory < ApplicationRecord
  belongs_to :category
  belongs_to :menu
  validates :category_id, presence: true
  validates :menu_id, presence: true
end

app/models/menu_tag.rb
class MenuTag < ApplicationRecord
  belongs_to :menu
  belongs_to :tag
  validates :menu_id, presence: true
  validates :tag_id, presence: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :menus
  geocoded_by :address
  after_validation :geocode, if: lambda {|obj| obj.address_changed?}
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :menu_tags
  has_many :menus, through: :menu_tags
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_many :user_menus
  has_many :menus, through: :user_menus

# 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                BCrypt::Engine.cost
                                                BCrypt::Password.create(string, cost: cost)
  end

# ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/models/user_menu.rb
class UserMenu < ApplicationRecord
  belongs_to :user
  belongs_to :menu
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end
  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
   session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # 現在のユーザーをログアウトする
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

# アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Healtheats</a>
    by <a href="http://www.michaelhartl.com/">Awesome Ars Academia </a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<button class="openMenuBtn" onClick="openMenu();">
  <span class="openMenuBtn-hamburger"></span>
  <span class="openMenuBtn-hamburger"></span>
  <span class="openMenuBtn-hamburger"></span>
</button>
<header>
  <div class="container navbar navbar-fixed-top navbar-inverse">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Healtheats", '/', id: "logo" %></li>
        <li><%= link_to "Tags", "#" %></li>
        <li><%= link_to "Activities", activities_path %></li>
        <li><%= link_to "Log in", login_path %></li>
        <button class="closeMenuBtn" onClick="closeMenu();">close</button>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Healtheats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>